version: "3"
services:
  db:
    image: postgres:14.7
    restart: no
    environment:
      - POSTGRES_USER=<YOUR_USERNAME>
      - POSTGRES_PASSWORD=<YOUR_PASSWORD>
    
    ports:
      - "10081:5432"

    volumes:
      - ./database_creation.sql:/docker-entrypoint-initdb.d/database_creation.sql
      - ./postgres-data:/var/database/PostgresTotem

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    working_dir: /app
    environment:
      - BB_WHITELIST_IP=172.18.0.1,175.15.1.2 # Comma-separated, don't use "" to wrap value just plain text
    ports:
      - "10481:10481"
    volumes:
      - .:/app
      - ./photos:/app/photos #'../photos' is a folder on the host
    depends_on:
      - db

volumes:
  postgres-data:

    
