version: "3"
services:
  db:
    image: postgres:14.7
    restart: always
    environment:
      - POSTGRES_USER=<YOUR_USERNAME>
      - POSTGRES_PASSWORD=<YOUR_PASSWORD>
    
    ports:
      - "5432:5432"

    volumes:
        - ./database_creation.sql:/docker-entrypoint-initdb.d/database_creation.sql
        - postgres-data:/var/database/PostgresTotem

  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "10481:10481"
    volumes:
      - .:/app
      - ../photos:/app/photos #'../photos' is a folder on the host
    depends_on:
      - db
    

volumes:
  postgres-data:

    
